language: node_js
node_js:
  - "6"
cache:
  directories:
    - "new marvin/node_modules"
env:
  - SOLIDITY_COVERAGE=true
before_script:
  - truffle version
install:
  - cd Marvin
  - npm install -g truffle
  - npm install -g ganache-cli
  - ./new marvin/npm install
script:
  - chmod +x. ./new marvin/startBlockchain.ps1
  - ./new marvin/startBlockchain.ps1 > /dev/null &
  - sleep 5
  - ./new marvin/truffle compile
  - ./new marvin/truffle migrate
  - ./new marvin/npm test