language: node_js
node_js:
  - "6"
cache:
  directories:
    - "new marvin/node_modules"
env:
  - SOLIDITY_COVERAGE=true
before_script:
  - truffle version
install:
  - cd "new marvin"
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - cd "new marvin"
  - chmod +x. startBlockchain.ps1
  - ./startBlockchain.ps1 > /dev/null &
  - sleep 5
  - truffle compile
  - truffle migrate
  - npm test