export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const FETCH_DATA_EMPTY = 'FETCH_DATA_EMPTY'
export const ERASE_ADMIN_REDUCER = 'ERASE_ADMIN_REDUCER'

export const ADDING = 'ADDING'
export const ADDED_NEW_DATA = 'ADDED_NEW_DATA'
export const ERROR_ADDING_NEW_DATA = 'ERROR_ADDING_NEW_DATA'

export const DELETING = 'DELETING'
export const DELETED_DATA = 'DELETED_DATA'
export const ERROR_DELETING_DATA = 'ERROR_DELETING_DATA'

// constants for managing the data retrieving
// request:
export const ACADEMIC_YEARS = 'ACADEMIC_YEAR'
export const DEGREE_COURSES = 'DEGREE_COURSES'
export const COURSES = 'COURSES'

export const ERASE_ACADEMIC_YEARS = 'ERASE_ACADEMIC_YEAR'
export const ERASE_DEGREE_COURSES = 'ERASE_DEGREE_COURSES'
export const ERASE_COURSES = 'ERASE_COURSES'

export const TEACHERS = 'TEACHERS'
export const STUDENTS = 'STUDENTS'
export const ADMINS = 'ADMINS'

export const ERASE_TEACHERS = 'ERASE_TEACHERS'
export const ERASE_STUDENTS = 'ERASE_STUDENTS'
export const ERASE_ADMINS = 'ERASE_ADMINS'