export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const FETCH_DATA_EMPTY = 'FETCH_DATA_EMPTY'
export const ERASE_ADMIN_REDUCER = 'ERASE_ADMIN_REDUCER'

export const ADDING = 'ADDING'
export const ADDED_NEW_DATA = 'ADDED_NEW_DATA'
export const ERROR_ADDING_NEW_DATA = 'ERROR_ADDING_NEW_DATA'