export const IPFS_CONNECTED = 'IPFS_CONNECTED'
export const IPFS_NOT_RESPONDING = 'IPFS_NOT_RESPONDING'

export const IPFS_ADDING_DATA = 'IPFS_ADDING_DATA'
export const IPFS_DATA_ADDED = 'IPFS_DATA_ADDED'
export const IPFS_ERROR_ADDING_DATA = 'IPFS_ERROR_ADDING_DATA'

export const IPFS_READING_DATA = 'IPFS_READING_DATA'
export const IPFS_DATA_READ = 'IPFS_DATA_READ'
export const IPFS_ERROR_READING_DATA = 'IPFS_ERROR_READING_DATA'

export const ERASE_IPFS_REDUCER = 'ERASE_IPFS_REDUCER'