language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
env:
  - SOLIDITY_COVERAGE=true
before_script:
  - truffle version
install:
  - cd Marvin
  - npm install -g truffle
  - npm install ganache-cli
  - npm install
script:
  - chmod +x startBlockchain.bat
  - ./startBlockchain.bat > /dev/null &
  - sleep 5
  - truffle compile
  - truffle migrate
  - npm test