export const EXAMS = "STUDENT_EXAMS"
export const SUBSCRIBED_EXAMS = "SUBSCRIBED_EXAMS"
export const BOOKLET = "BOOKLET"

export const ERASE_EXAMS = "TEACHER_ERASE_EXAMS"
export const ERASE_SUBSCRIBED_EXAMS = "ERASE_SUBSCRIBED_EXAMS"
export const ERASE_BOOKLET = "ERASE_BOOKLET"