export const CLASSES = 'TEACHER_CLASSES'
export const EXAMS = "TEACHER_EXAMS"
export const STUDENTS = 'TEACHER_STUDENTS'

export const ERASE_CLASSES = "TEACHER_ERASE_CLASSES"
export const ERASE_EXAMS = "TEACHER_ERASE_EXAMS"
export const ERASE_STUDENTS = 'TEACHER_ERASE_STUDENTS'