export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const TRYING_METAMASK = 'TRYING_METAMASK'

export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'
export const FETCH_DATA_EMPTY = 'FETCH_DATA_EMPTY'

export const ADDING = 'ADDING'
export const ADDED_NEW_DATA = 'ADDED_NEW_DATA'
export const ERROR_ADDING_NEW_DATA = 'ERROR_ADDING_NEW_DATA'

export const DELETING = 'DELETING'
export const DELETED_DATA = 'DELETED_DATA'
export const ERROR_DELETING_DATA = 'ERROR_DELETING_DATA'